module.exports = function () {
  return {
    'free-solid-svg-icons': [
      'building',
      'user',
      'map-pin',
      'chalkboard-user',
      'graduation-cap',
      'stamp',
      'clipboard-list',
      'signs-post',
      'users',
      'book-open',
      'screwdriver-wrench',
      'crown',
      'power-off',
      'chevron-down',
      'chevron-up',
      'check',
      'arrow-left',
      'arrow-right',
      'xmark',
      'triangle-exclamation',
      'arrows-rotate',
      'circle-exclamation',
      'arrow-up-right-from-square',
      'trash',
      'pen-to-square',
      'check-double',
      'tablet-screen-button',
      'mobile-screen-button',
      'slash',
      'plus',
      'circle-xmark',
      'circle-check',
      'circle-info',
      'circle-question',
      'magnifying-glass',
      'chevron-right',
      'external-link',
      'eye',
      'times',
      'warning',
      'message',
    ],
    'free-regular-svg-icons': ['copy'],
  };
};
