const keys = {
  PIX_EMPLOI_CLEA_V1: 'PIX_EMPLOI_CLEA',
  PIX_EMPLOI_CLEA_V2: 'PIX_EMPLOI_CLEA_V2',
  PIX_EMPLOI_CLEA_V3: 'PIX_EMPLOI_CLEA_V3',
  PIX_DROIT_MAITRE_CERTIF: 'PIX_DROIT_MAITRE_CERTIF',
  PIX_DROIT_EXPERT_CERTIF: 'PIX_DROIT_EXPERT_CERTIF',
  PIX_EDU_FORMATION_INITIALE_2ND_DEGRE_INITIE: 'PIX_EDU_FORMATION_INITIALE_2ND_DEGRE_INITIE',
  PIX_EDU_FORMATION_INITIALE_2ND_DEGRE_CONFIRME: 'PIX_EDU_FORMATION_INITIALE_2ND_DEGRE_CONFIRME',
  PIX_EDU_FORMATION_CONTINUE_2ND_DEGRE_CONFIRME: 'PIX_EDU_FORMATION_CONTINUE_2ND_DEGRE_CONFIRME',
  PIX_EDU_FORMATION_CONTINUE_2ND_DEGRE_AVANCE: 'PIX_EDU_FORMATION_CONTINUE_2ND_DEGRE_AVANCE',
  PIX_EDU_FORMATION_CONTINUE_2ND_DEGRE_EXPERT: 'PIX_EDU_FORMATION_CONTINUE_2ND_DEGRE_EXPERT',
  PIX_EDU_FORMATION_INITIALE_1ER_DEGRE_INITIE: 'PIX_EDU_FORMATION_INITIALE_1ER_DEGRE_INITIE',
  PIX_EDU_FORMATION_INITIALE_1ER_DEGRE_CONFIRME: 'PIX_EDU_FORMATION_INITIALE_1ER_DEGRE_CONFIRME',
  PIX_EDU_FORMATION_CONTINUE_1ER_DEGRE_CONFIRME: 'PIX_EDU_FORMATION_CONTINUE_1ER_DEGRE_CONFIRME',
  PIX_EDU_FORMATION_CONTINUE_1ER_DEGRE_AVANCE: 'PIX_EDU_FORMATION_CONTINUE_1ER_DEGRE_AVANCE',
  PIX_EDU_FORMATION_CONTINUE_1ER_DEGRE_EXPERT: 'PIX_EDU_FORMATION_CONTINUE_1ER_DEGRE_EXPERT',
};

export const badges = { keys };
