export const PGSQL_DUPLICATE_DATABASE_ERROR = '42P04';
export const PGSQL_DUPLICATE_SCHEMA_ERROR = '42P06';
export const PGSQL_NON_EXISTENT_DATABASE_ERROR = '3D000';
export const PGSQL_UNIQUE_CONSTRAINT_VIOLATION_ERROR = '23505';
export const PGSQL_FOREIGN_KEY_VIOLATION_ERROR = '23503';
