const PGSQL_DUPLICATE_DATABASE_ERROR = '42P04';
const PGSQL_NON_EXISTENT_DATABASE_ERROR = '3D000';
const PGSQL_UNIQUE_CONSTRAINT_VIOLATION_ERROR = '23505';

module.exports = {
  PGSQL_DUPLICATE_DATABASE_ERROR,
  PGSQL_NON_EXISTENT_DATABASE_ERROR,
  PGSQL_UNIQUE_CONSTRAINT_VIOLATION_ERROR,
};
