extends: 'eslint:recommended'
root: true
plugins:
  - mocha
parserOptions:
  ecmaVersion: 2018
  sourceType: script
env:
  es6: true
  node: true
rules:
  arrow-parens:
    - error
    - always
  comma-dangle:
    - error
    - "always-multiline"
  computed-property-spacing:
    - error
    - never
  eol-last:
    - error
  indent:
    - error
    - 2
    - SwitchCase: 1
  keyword-spacing:
    - error
  linebreak-style:
    - error
    - unix
  "mocha/no-exclusive-tests":
    - error
  "mocha/no-identical-title":
    - error
  "mocha/no-skipped-tests":
    - warn
  no-multiple-empty-lines:
    - error
    - { max: 1, maxEOF: 1 }
  no-restricted-syntax:
    - error
    # Use https://estools.github.io/esquery/ to test selector
    # These rules are overridden in /api/.eslintrc.yaml - In case adding one here, add it also in /api/.eslintrc.yaml
    - selector: "NewExpression[callee.name=Date][arguments.length=1][arguments.0.type=Literal]:not([arguments.0.value=/^[12][0-9]{3}-(0[0-9]|1[0-2])-([0-2][0-9]|3[01])(T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]Z)?$/])"
      message: "Use only ISO8601 UTC syntax ('2019-03-12T01:02:03Z') in Date constructor"
    - selector: "CallExpression[callee.object.object.name='faker'][callee.object.property.name='internet'][callee.property.name='email']"
      message: "Use only faker.internet.exampleEmail()"
  no-unused-vars:
    - error
    - { argsIgnorePattern: "_" }
  no-var:
    - error
  object-curly-spacing:
    - error
    - always
  prefer-const:
    - error
  quotes:
    - error
    - single
  semi:
    - error
    - always
  space-before-blocks:
    - error
  space-before-function-paren:
    - error
    - { anonymous: never, named: never, asyncArrow: ignore }
  space-in-parens:
    - error
  space-infix-ops:
    - error
