module.exports = [
  require('./application/answers'),
  require('./application/assessments'),
  require('./application/authentication'),
  require('./application/cache'),
  require('./application/challenges'),
  require('./application/courses'),
  require('./application/courseGroups'),
  require('./application/simulateErrors'),
  require('./application/feedbacks'),
  require('./application/followers'),
  require('./application/healthcheck'),
  require('./application/metrics'),
  require('./application/organizations'),
  require('./application/snapshots'),
  require('./application/users'),
];
