apiVersion: v1
kind: ConfigMap
metadata:
  name: admin-config
  namespace: pix
data:
  API_HOST: "https://pix-api.ccaya.cc"
  DEFAULT_LOCALE: "fr"
  PIX_APP_URL_WITHOUT_EXTENSION: "https://pix-app.ccaya."
