POST {{baseUrl}}/api/audit-logs
Content-Type: application/json

{"targetUserId": "2", "userId": "3", "action": "ANONYMIZATION", "occurredAt": "2023-08-04T08:57:54.836Z", "role": "SUPPORT", "client": "PIX_ADMIN"}

> {%
client.test('Creates an audit log and returns a response with an HTTP status code 204 (NO_CONTENT)', function () {
  client.assert(response.status === 204, `Server responded with HTTP status code ${response.status}`)
});
 %}
