---
version: 2

jobs:
  build:
    docker:
      - image: circleci/node:latest-browsers
    working_directory: ~/pix-orga
    steps:
      - checkout
      - run: npm install
      - run: echo "${CIRCLE_BRANCH}_${CIRCLE_SHA1}" > .circle-cache-key
      - save_cache:
          key: v3-pix-orga-{{ checksum ".circle-cache-key" }}
          paths:
            - ~/pix-orga

  test:
    docker:
      - image: circleci/node:latest-browsers
    working_directory: ~/pix-orga
    steps:
      - run: echo "${CIRCLE_BRANCH}_${CIRCLE_SHA1}" > .circle-cache-key
      - restore_cache:
          key: v3-pix-orga-{{ checksum ".circle-cache-key" }}
      - run: npm test

  deploy:
    docker:
      - image: circleci/node:latest-browsers
    working_directory: ~/pix-orga
    steps:
      - run: echo "${CIRCLE_BRANCH}_${CIRCLE_SHA1}" > .circle-cache-key
      - restore_cache:
          key: v3-pix-orga-{{ checksum ".circle-cache-key" }}
      - add_ssh_keys:
          fingerprints:
            - "d8:07:94:de:70:24:96:32:7f:e0:ac:e6:80:dd:0e:9a"
      - run: ssh-keyscan scalingo.com > ~/.ssh/known_hosts
      - run: |
          git config user.email "$GITHUB_EMAIL"
          git config user.name "$GITHUB_NAME"
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              git remote add scalingo git@scalingo.com:pix-orga.git
              git push --force scalingo master:master
            elif [ "${CIRCLE_BRANCH}" == "dev" ]; then
              git remote add scalingo git@scalingo.com:pix-orga-integration.git
              git push --force scalingo dev:master
            fi

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - build
            - test
          filters:
            branches:
              only:
                - dev
                - master
