services:
  caddy:
    container_name: caddy
    image: caddy:latest@sha256:df7f1c2fb114453b951de51a98efc010db1655a92c2e86be6706714e2417a78d
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      - API_HOST=host.docker.internal
volumes:
  caddy_data:
    external: false
  caddy_config:
    external: false
