config:
  processor: "../functions.js"
  environments:
    localhost:
      target: http://localhost:3000
    development:
      target: "{{ $processEnvironment.TARGET_DEV_API_URL }}"
    staging:
      target: https://integration.pix.fr
