config:
  processor: "../functions.js"
  environments:
    localhost:
      target: http://localhost:3000
    development:
      target: https://pix-api-load-testing.osc-fr1.scalingo.io
    staging:
      target: https://integration.pix.fr
