FROM node:20.13.0 as dev

WORKDIR /code
COPY . .

RUN npm ci
RUN npm install -g ember-cli 

CMD [ "npm", "run", "start:watch" ]

FROM dev as builder
ENV BUILD_ENV=dev

RUN npx ember build --env $BUILD_ENV

FROM nginx:1.26.0 as production

COPY --from=builder /code/dist/ /usr/share/nginx/html/
