version: 2.1

parameters:
  build-and-test-api:
    type: boolean
    default: false
  build-and-test:
    type: boolean
    default: false

orbs:
  browser-tools: circleci/browser-tools@1.2.4
  slack: circleci/slack@4.9.3

workflows:
  version: 2
  build-and-test-api:
    when: << pipeline.parameters.build-and-test-api >>
    jobs:
      - checkout:
          context: Pix

      - api_build_and_test:
          context: Pix
          requires:
            - checkout

  build-and-test:
    when: << pipeline.parameters.build-and-test >>
    jobs:
      - checkout:
          context: Pix

      - mon_pix_build_and_test:
          context: Pix
          requires:
            - checkout

      - orga_build_and_test:
          context: Pix
          requires:
            - checkout

      - certif_build_and_test:
          context: Pix
          requires:
            - checkout

      - admin_build_and_test:
          context: Pix
          requires:
            - checkout

      - e2e_test:
          context: Pix
          requires:
            - checkout

      - algo_test:
          context: Pix
          requires:
            - checkout

jobs:
  checkout:
    docker:
      - image: cimg/node:16.14.0
    resource_class: small
    working_directory: ~/pix
    steps:
      - checkout
      - run:
          name: Lint and test root
          command: |
            npm ci
            npm run lint:scripts
            npm run lint:yaml
            npm run test:root
            rm -rf .git/
      - persist_to_workspace:
          root: ~/pix
          paths:
            - .
      - notify-ci-errors-on-slack

  api_build_and_test:
    docker:
      - image: cimg/node:16.14.0
      - image: postgres:13.7-alpine
        environment:
          POSTGRES_USER: circleci
          POSTGRES_HOST_AUTH_METHOD: trust
      - image: redis:6.2.7-alpine
    resource_class: small
    working_directory: ~/pix/api
    steps:
      - attach_workspace:
          at: ~/pix
      - run: cat package*.json > cachekey
      - restore_cache:
          keys:
            - v7-api-npm-{{ checksum "cachekey" }}
      - run: npm ci --no-optional
      - save_cache:
          key: v7-api-npm-{{ checksum "cachekey" }}
          paths:
            - ~/.npm
      - run:
          name: Lint and test
          command: |
            npm run lint
            npm run test:ci
          environment:
            TEST_DATABASE_URL: postgres://circleci@localhost:5432/circleci
            TEST_REDIS_URL: redis://localhost:6379
            MOCHA_FILE: /home/circleci/test-results/test-results.[hash].xml
            MOCHA_REPORTER: mocha-junit-reporter
          when: always
      - store_test_results:
          path: /home/circleci/test-results
      - store_artifacts:
          path: /home/circleci/test-results
      - notify-ci-errors-on-slack

  mon_pix_build_and_test:
    docker:
      - image: cimg/node:16.14.0-browsers
        environment:
          # See https://git.io/vdao3 for details.
          JOBS: 2
    working_directory: ~/pix/mon-pix
    parallelism: 3
    steps:
      - browser-tools/install-chrome
      - attach_workspace:
          at: ~/pix
      - run: cat package*.json > cachekey
      - restore_cache:
          keys:
            - v7-mon-pix-npm-{{ checksum "cachekey" }}
      - run: npm ci
      - save_cache:
          key: v7-mon-pix-npm-{{ checksum "cachekey" }}
          paths:
            - ~/.npm
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Test
          command: npm run test:ci
      - notify-ci-errors-on-slack

  orga_build_and_test:
    docker:
      - image: cimg/node:16.14.0-browsers
        environment:
          JOBS: 2
    resource_class: small
    working_directory: ~/pix/orga
    steps:
      - browser-tools/install-chrome
      - attach_workspace:
          at: ~/pix
      - run: cat package*.json > cachekey
      - restore_cache:
          keys:
            - v7-orga-npm-{{ checksum "cachekey" }}
      - run: npm ci
      - save_cache:
          key: v7-orga-npm-{{ checksum "cachekey" }}
          paths:
            - ~/.npm
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Test
          command: npm run test:ci
      - notify-ci-errors-on-slack

  certif_build_and_test:
    docker:
      - image: cimg/node:16.14.0-browsers
        environment:
          JOBS: 2
    resource_class: small
    working_directory: ~/pix/certif
    steps:
      - browser-tools/install-chrome
      - attach_workspace:
          at: ~/pix
      - run: cat package*.json > cachekey
      - restore_cache:
          keys:
            - v7-certif-npm-{{ checksum "cachekey" }}
      - run: npm ci
      - save_cache:
          key: v7-certif-npm-{{ checksum "cachekey" }}
          paths:
            - ~/.npm
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Test
          command: npm run test:ci
      - notify-ci-errors-on-slack

  admin_build_and_test:
    docker:
      - image: cimg/node:16.14.0-browsers
        environment:
          JOBS: 2
    resource_class: small
    working_directory: ~/pix/admin
    steps:
      - browser-tools/install-chrome
      - attach_workspace:
          at: ~/pix
      - run: cat package*.json > cachekey
      - restore_cache:
          keys:
            - v7-admin-npm-{{ checksum "cachekey" }}
      - run: npm ci
      - save_cache:
          key: v7-admin-npm-{{ checksum "cachekey" }}
          paths:
            - ~/.npm
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Test
          command: npm run test:ci
      - notify-ci-errors-on-slack

  e2e_test:
    docker:
      - image: cimg/node:16.14.0-browsers
      - image: postgres:13.7-alpine
        environment:
          POSTGRES_USER: circleci
          POSTGRES_HOST_AUTH_METHOD: trust
      - image: redis:6.2.7-alpine
    resource_class: medium+
    parallelism: 5
    working_directory: ~/pix/high-level-tests/e2e
    steps:
      - browser-tools/install-chrome
      - attach_workspace:
          at: ~/pix
      - run: cat package*.json > cachekey
      - restore_cache:
          keys:
            - v7-e2e-npm-{{ checksum "cachekey" }}
      - run: npm ci
      - save_cache:
          key: v7-e2e-npm-{{ checksum "cachekey" }}
          paths:
            - ~/.npm

      - run:
          name: Lint
          command: npm run lint

      - run:
          working_directory: ~/pix/api
          command: cat package*.json > cachekey
      - restore_cache:
          keys:
            - v7-api-npm-{{ checksum "~/pix/api/cachekey" }}
      - run:
          name: Install Pix API
          working_directory: ~/pix/api
          command: npm ci --no-optional

      - run:
          working_directory: ~/pix/mon-pix
          command: cat package*.json > cachekey
      - restore_cache:
          keys:
            - v7-mon-pix-npm-{{ checksum "~/pix/mon-pix/cachekey" }}
      - run:
          name: Install Pix App
          environment:
            JOBS: 1
          working_directory: ~/pix/mon-pix
          command: npm ci

      - run:
          working_directory: ~/pix/orga
          command: cat package*.json > cachekey
      - restore_cache:
          keys:
            - v7-orga-npm-{{ checksum "~/pix/orga/cachekey" }}
      - run:
          name: Install Pix Orga
          environment:
            JOBS: 2
          working_directory: ~/pix/orga
          command: npm ci

      - run:
          name: Start Pix API
          working_directory: ~/pix/api
          environment:
            DATABASE_URL: 'postgres://circleci@localhost:5432/circleci'
            REDIS_URL: 'redis://localhost:6379'
          background: true
          command: npm start

      - run:
          name: Start Pix App
          working_directory: ~/pix/mon-pix
          environment:
            JOBS: 1
          background: true
          command: npm start

      - run:
          name: Start Pix Orga
          working_directory: ~/pix/orga
          environment:
            JOBS: 2
          background: true
          command: npm start

      - run:
          name: Run tests
          environment:
            DATABASE_URL: 'postgres://circleci@localhost:5432/circleci'
          command: npm run test:ci
      - store_test_results:
          path: /home/circleci/test-results
      - notify-ci-errors-on-slack

  algo_test:
    docker:
      - image: cimg/node:16.14.0
    resource_class: small
    parallelism: 1
    working_directory: ~/pix/high-level-tests/test-algo
    steps:
      - attach_workspace:
          at: ~/pix
      - run:
          working_directory: ~/pix/api
          command: cat package*.json > cachekey
      - restore_cache:
          keys:
            - v7-api-npm-{{ checksum "~/pix/api/cachekey" }}
      - run:
          name: Install Pix API
          working_directory: ~/pix/api
          environment:
            DATABASE_URL: 'postgres://circleci@localhost:5432/circleci'
          command: npm ci --no-optional
      - run:
          command: cat package*.json > cachekey

      - restore_cache:
          keys:
            - v7-test-algo-npm-{{ checksum "~/pix/high-level-tests/test-algo/cachekey" }}
      - run:
          name: Install test algo
          command: npm ci
      - save_cache:
          key: v7-test-algo-npm-{{ checksum "~/pix/high-level-tests/test-algo/cachekey" }}
          paths:
            - ~/.npm

      - run:
          name: Lint
          command: npm run lint

      - run:
          name: Test
          command: npm run test:ci
      - notify-ci-errors-on-slack

commands:
  notify-ci-errors-on-slack:
    steps:
      - slack/notify:
          event: fail
          channel: engineering
          branch_pattern: dev
