module.exports = {
  authenticateUser: require('./authenticate-user'),
  createCampaign: require('./create-campaign'),
  createAssessmentResultForCompletedCertification: require('./create-assessment-result-for-completed-certification'),
  createAssessmentForCampaign: require('./create-assessment-for-campaign'),
  createUser: require('./create-user'),
  findCompletedUserCertifications: require('./find-completed-user-certifications'),
  findUserAssessmentsByFilters: require('./find-user-assessments-by-filters'),
  getCorrectionForAnswerWhenAssessmentEnded: require('./get-correction-for-answer-when-assessment-ended'),
  getNextChallengeForCertification: require('./get-next-challenge-for-certification'),
  getNextChallengeForDemo: require('./get-next-challenge-for-demo'),
  getNextChallengeForPlacement: require('./get-next-challenge-for-placement'),
  getNextChallengeForPreview: require('./get-next-challenge-for-preview'),
  getNextChallengeForSmartPlacement: require('./get-next-challenge-for-smart-placement'),
  getResultsCampaignInCSVFormat: require('./get-results-campaign-in-csv-format'),
  getOrganizationCampaigns: require('./get-organization-campaigns'),
  getSkillReview: require('./get-skill-review'),
  getUserCertification: require('./get-user-certification'),
  getUserCertificationWithResultTree: require('./get-user-certification-with-result-tree'),
  getUserWithOrganizationAccesses: require('./get-user-with-organization-accesses'),
  preloadCacheEntries: require('./preload-cache-entries'),
  removeAllCacheEntries: require('./remove-all-cache-entries'),
  removeCacheEntry: require('./remove-cache-entry'),
  correctAnswerThenUpdateAssessment: require('./correct-answer-then-update-assessment'),
  updateCertification: require('./update-certification'),
};
