module.exports = {
  buildAnswer: require('./build-answer'),
  buildAssessment: require('./build-assessment'),
  buildAssessmentResult: require('./build-assessment-result'),
  buildCampaign: require('./build-campaign'),
  buildCampaignParticipation: require('./build-campaign-participation'),
  buildCompetenceEvaluation: require('./build-competence-evaluation'),
  buildCertificationCenter: require('./build-certification-center'),
  buildCertificationCenterMembership: require('./build-certification-center-membership'),
  buildCertificationChallenge: require('./build-certification-challenge'),
  buildCertificationCourse: require('./build-certification-course'),
  buildOrganization: require('./build-organization'),
  buildOrganizationRole: require('./build-organization-role'),
  buildMembership: require('./build-membership'),
  buildPixRole: require('./build-pix-role'),
  buildSmartPlacementKnowledgeElement: require('./build-smart-placement-knowledge-element'),
  buildSnapshot: require('./build-snapshot'),
  buildSession: require('./build-session'),
  buildTargetProfile: require('./build-target-profile'),
  buildTargetProfilesSkills: require('./build-target-profiles-skills'),
  buildTargetProfileShare: require('./build-target-profile-share'),
  buildUser: require('./build-user'),
  buildUserPixRole: require('./build-user-pix-role'),
};
