module.exports = {
  buildAnswer: require('./build-answer'),
  buildAssessment: require('./build-assessment'),
  buildAssessmentResult: require('./build-assessment-result'),
  buildCampaign: require('./build-campaign'),
  buildCampaignParticipation: require('./build-campaign-participation'),
  buildCertificationCenter: require('./build-certification-center'),
  buildCertificationCenterMembership: require('./build-certification-center-membership'),
  buildCertificationChallenge: require('./build-certification-challenge'),
  buildCertificationCourse: require('./build-certification-course'),
  buildCompetenceEvaluation: require('./build-competence-evaluation'),
  buildCompetenceMark: require('./build-competence-mark'),
  buildKnowledgeElement: require('./build-knowledge-element'),
  buildMembership: require('./build-membership'),
  buildOrganization: require('./build-organization'),
  buildPasswordResetDemand: require('./build-password-reset-demand'),
  buildPixRole: require('./build-pix-role'),
  buildSession: require('./build-session'),
  buildSnapshot: require('./build-snapshot'),
  buildTargetProfile: require('./build-target-profile'),
  buildTargetProfileShare: require('./build-target-profile-share'),
  buildTargetProfileSkill: require('./build-target-profile-skill'),
  buildUser: require('./build-user'),
  buildUserPixRole: require('./build-user-pix-role'),
};
