@startuml
actor Elève #blue
actor Professeur #green
participant PixOrga
participant MonPix
participant API

Elève -> MonPix : saisie de: \n identifiant = jean12345 \n mot de passe = JeanRulezz
note left: Connexion à app.pix.fr \n (ancien MDP)
MonPix -> API : POST /api/token \ngrant_type=password&username=jean12345\n&password=JeanRulezz&scope=mon-pix
API -> MonPix : 401 Unauthorized
MonPix -> Elève : L'adresse e-mail ou le mot de passe sont incorrects
Elève -> Professeur : "Je n'arrive pas à me connecter !"
Professeur -> PixOrga: "Quels sont les élèves ?" \n Clic sur Elèves
note left: Connexion du professeur à PixOrga
PixOrga -> API: GET /api/organizations/{id}/students
API -> PixOrga: { data: [ \n {type: "students", id:"100049", attributes: {username: "jean012345"} }, \n … ] }
PixOrga -> Professeur : Elèves\nIdentifiant: jean012345, …
Professeur -> PixOrga: Sur Jean, clic sur "Réinitialiser le mot de passe"
PixOrga -> API : POST ?
API -> PixOrga: 201 Created ? \n{ password: "Azerty123*"} ??
PixOrga -> Professeur : Azerty123*
Professeur -> Elève: Connecte-toi avec \n jean012345 / Azerty123*
Elève -> MonPix : saisie de \n identifiant = jean012345 \n Mot de passe = Azerty123*
note left: Connexion à app.pix.fr \n (MDP temporaire)
MonPix -> API : POST /api/token \n\ngrant_type=password&username=jean12345\n&password=Azerty123*&scope=mon-pix
API -> MonPix : 401 Unauthorized\n { errors: [ \n { status: "401", title: "PasswordExpired", detail:"Erreur, votre mot de passe est arrivé à expiration.} \n]}
MonPix -> MonPix : Go /update-expired-password
MonPix -> Elève : Vous devez choisir un nouveau mot de passe
Elève -> MonPix : JeanRulezz123
note left: Saisie du nouveau MDP
MonPix -> API : POST /api/expired-password-update \n{ data: { attributes: { \n username: "jean012345", expiredPassword:"Azerty123*", newPassword:"JeanRulezz123" \n}}}
API -> MonPix : 201 / Created \n{"data":{"type":"users"}}
MonPix -> MonPix : Go /connexion
MonPix -> API : POST /api/token\ngrant_type=password&username=jean12345\n&password=JeanRulezz123&scope=mon-pix
API -> MonPix : 200 OK \n{ token_type: "bearer", access_token:"…","user_id":104862}
MonPix -> Elève : "Vous avez X compétences à tester. \nOn se concentre et c'est partix !  "
@enduml
