version: '3'
services:
  datascience-notebook:
    build: .
    volumes:
      - ./:/home/jovyan
    ports:
      - 8888:8888
    container_name: jupyter_notebook
    command: "start-notebook.sh --ip='*' --NotebookApp.token='' --NotebookApp.password=''"
