export const COMPETENCE_TITLES = [
  'Mener une recherche et une veille d’information',
  'Gérer des données',
  'Traiter des données',
  'Interagir',
  'Partager et publier',
  'S’insérer dans le monde numérique',
  'Développer des documents textuels',
  'Développer des documents multimedia',
  'Adapter les documents à leur finalité',
  'Programmer',
  'Sécuriser l’environnement numérique',
  'Protéger les données personnelles et la vie privée',
  'Protéger la santé, le bien-être et l’environnement',
  'Résoudre des problèmes techniques',
  'Construire un environnement numérique',
];
