require('dotenv').config();
const parsePostgresqlConnectionString = require('pg-connection-string').parse;

const databaseToLint = {
  connexion: parsePostgresqlConnectionString(process.env.TEST_DATABASE_URL),
  schema: [{ name: 'public' }],
};

const rules = {
  settings: {
    'name-casing': ['error', 'snake'],
    'name-inflection': ['error', 'plural'],
  },
  ignores: [
    { identifierPattern: 'public\\.knex*.*', rulePattern: '.*' },
    { identifierPattern: 'public\\.badge-criteria', rulePattern: 'name-inflection' },
    { identifierPattern: 'public\\.account-recovery-demands', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.activities', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.activity-answers', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.answers', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.assessment-results', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.assessments', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.attestations', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.authentication-methods', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.badge-acquisitions', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.badge-criteria', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.badges', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.campaign-features', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.campaign-participations', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.campaign_skills', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.campaigns', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.certification-candidates', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.certification-center-features', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.certification-center-invitations', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.certification-center-memberships', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.certification-centers', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.certification-challenge-capacities', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.certification-challenge-live-alerts', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.certification-challenges', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.certification-companion-live-alerts', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.certification-courses', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.certification-courses-cpf-infos', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.certification-cpf-cities', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.certification-cpf-countries', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.certification-issue-reports', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.certification-scoring-configurations', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.certification-subscriptions', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.client_applications', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.competence-evaluations', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.competence-marks', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.competence-scoring-configurations', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.complementary-certification-badges', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.complementary-certification-course-results', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.complementary-certification-courses', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.complementary-certification-habilitations', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.complementary-certifications', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.data-protection-officers', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.element-answers', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.features', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.feedbacks', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.finalized-sessions', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.flash-algorithm-configurations', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.flash-assessment-results', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.issue-report-categories', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.knowledge-element-snapshots', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.knowledge-elements', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.last-user-application-connections', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.legal-document-version-user-acceptances', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.legal-document-versions', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.lti_platform_registrations', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.memberships', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.mission-assessments', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.oidc-providers', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.organization-features', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.organization-imports', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.organization-invitations', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.organization-learner-feature', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.organization-learner-import-formats', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.organization-learners', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.organization-places', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.organization-tags', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.organizations', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.organizations-profile-rewards', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.passage-events', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.passages', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.pix-admin-roles', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.pole-emploi-sendings', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.profile-rewards', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.quests', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.reset-password-demands', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.schools', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.sessions', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.stage-acquisitions', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.stages', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.supervisor-accesses', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.tags', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.target-profile-shares', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.target-profile-trainings', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.target-profile_tubes', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.target-profiles', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.training-trigger-tubes', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.training-triggers', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.trainings', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.tutorial-evaluations', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.user-logins', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.user-orga-settings', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.user-recommended-trainings', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.user-saved-tutorials', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.users', rulePattern: 'name-casing' },
    { identifierPattern: 'public\\.view-active-organization-learners', rulePattern: 'name-casing' },
  ],
};

const configuration = {
  connection: databaseToLint.connexion,
  schemas: databaseToLint.schema,
  rules: rules.settings,
  ignores: rules.ignores,
};

module.exports = configuration;
