module.exports = {
  CertificationIssueReportCategories: {
    OTHER: 'OTHER',
    CANDIDATE_INFORMATIONS_CHANGES: 'CANDIDATE_INFORMATIONS_CHANGES',
    LATE_OR_LEAVING: 'LATE_OR_LEAVING',
    CONNECTION_OR_END_SCREEN: 'CONNECTION_OR_END_SCREEN',
  },
  CertificationIssueReportSubcategories: {
    NAME_OR_BIRTHDATE: 'NAME_OR_BIRTHDATE',
    EXTRA_TIME_PERCENTAGE: 'EXTRA_TIME_PERCENTAGE',
    LEFT_EXAM_ROOM: 'LEFT_EXAM_ROOM',
    SIGNATURE_ISSUE: 'SIGNATURE_ISSUE',
    SKIP_QUESTION_MISSING_TIME: 'SKIP_QUESTION_MISSING_TIME',
  },
};
