module.exports = {
  CertificationIssueReportCategories: {
    OTHER: 'OTHER',
    CANDIDATE_INFORMATIONS_CHANGES: 'CANDIDATE_INFORMATIONS_CHANGES',
    LATE_OR_LEAVING: 'LATE_OR_LEAVING',
    CONNECTION_OR_END_SCREEN: 'CONNECTION_OR_END_SCREEN',
    IN_CHALLENGE: 'IN_CHALLENGE',
    FRAUD: 'FRAUD',
  },
  CertificationIssueReportSubcategories: {
    NAME_OR_BIRTHDATE: 'NAME_OR_BIRTHDATE',
    EXTRA_TIME_PERCENTAGE: 'EXTRA_TIME_PERCENTAGE',
    LEFT_EXAM_ROOM: 'LEFT_EXAM_ROOM',
    SIGNATURE_ISSUE: 'SIGNATURE_ISSUE',
    IMAGE_NOT_DISPLAYING: 'IMAGE_NOT_DISPLAYING',
    LINK_NOT_WORKING: 'LINK_NOT_WORKING',
    EMBED_NOT_WORKING: 'EMBED_NOT_WORKING',
    FILE_NOT_OPENING: 'FILE_NOT_OPENING',
    WEBSITE_UNAVAILABLE: 'WEBSITE_UNAVAILABLE',
    WEBSITE_BLOCKED: 'WEBSITE_BLOCKED',
    OTHER: 'OTHER',
  },
};
