// the following list of imports has been generated by the commented code

// import * as url from 'url';
// const __dirname = url.fileURLToPath(new URL('.', import.meta.url));

// import fs from 'fs';
// import path from 'path';

// fs.readdir(__dirname, { withFileTypes: true }, (err, dirents) => {
//   dirents.forEach((dirent) => {
//     if (!dirent.isFile() || dirent.name === 'index.js') return;
//     console.log(`import ${path.basename(dirent.name, '.js')} from './${dirent.name}';`);
//   });
// });

import AccountRecoveryDemand from './AccountRecoveryDemand.js';
import AdminMember from './AdminMember.js';
import Answer from './Answer.js';
import AnswerCollectionForScoring from './AnswerCollectionForScoring.js';
import AnswerStatus from './AnswerStatus.js';
import Area from './Area.js';
import Assessment from './Assessment.js';
import AssessmentResult from './AssessmentResult.js';
import Authentication from './Authentication.js';
import AuthenticationMethod from './AuthenticationMethod.js';
import AuthenticationSessionContent from './AuthenticationSessionContent.js';
import Badge from './Badge.js';
import BadgeAcquisition from './BadgeAcquisition.js';
import BadgeCriterion from './BadgeCriterion.js';
import BadgeDetails from './BadgeDetails.js';
import BadgeForCalculation from './BadgeForCalculation.js';
import Campaign from './Campaign.js';
import CampaignCreator from './CampaignCreator.js';
import CampaignForArchiving from './CampaignForArchiving.js';
import CampaignForCreation from './CampaignForCreation.js';
import CampaignLearningContent from './CampaignLearningContent.js';
import CampaignParticipant from './CampaignParticipant.js';
import CampaignParticipation from './CampaignParticipation.js';
import CampaignParticipationBadge from './CampaignParticipationBadge.js';
import CampaignParticipationResult from './CampaignParticipationResult.js';
import CampaignParticipationStatuses from './CampaignParticipationStatuses.js';
import CampaignToStartParticipation from './CampaignToStartParticipation.js';
import CampaignTypes from './CampaignTypes.js';
import CertifiableBadgeAcquisition from './CertifiableBadgeAcquisition.js';
import CertifiableProfileForLearningContent from './CertifiableProfileForLearningContent.js';
import CertificationAnswerStatusChangeAttempt from './CertificationAnswerStatusChangeAttempt.js';
import CertificationAssessment from './CertificationAssessment.js';
import CertificationAssessmentScore from './CertificationAssessmentScore.js';
import CertificationAttestation from './CertificationAttestation.js';
import CertificationCandidate from './CertificationCandidate.js';
import CertificationCandidateForSupervising from './CertificationCandidateForSupervising.js';
import CertificationCenter from './CertificationCenter.js';
import CertificationCenterForAdmin from './CertificationCenterForAdmin.js';
import CertificationCenterInvitation from './CertificationCenterInvitation.js';
import CertificationCenterInvitedUser from './CertificationCenterInvitedUser.js';
import CertificationCenterMembership from './CertificationCenterMembership.js';
import CertificationChallenge from './CertificationChallenge.js';
import CertificationChallengeWithType from './CertificationChallengeWithType.js';
import CertificationContract from './CertificationContract.js';
import CertificationCourse from './CertificationCourse.js';
import CertificationCpfCity from './CertificationCpfCity.js';
import CertificationCpfCountry from './CertificationCpfCountry.js';
import CertificationIssueReport from './CertificationIssueReport.js';
import CertificationIssueReportCategory from './CertificationIssueReportCategory.js';
import CertificationIssueReportResolutionAttempt from './CertificationIssueReportResolutionAttempt.js';
import CertificationIssueReportResolutionStrategies from './CertificationIssueReportResolutionStrategies.js';
import CertificationOfficer from './CertificationOfficer.js';
import CertificationReport from './CertificationReport.js';
import CertificationResult from './CertificationResult.js';
import CertifiedLevel from './CertifiedLevel.js';
import CertifiedScore from './CertifiedScore.js';
import Challenge from './Challenge.js';
import Competence from './Competence.js';
import CompetenceEvaluation from './CompetenceEvaluation.js';
import CompetenceMark from './CompetenceMark.js';
import CompetenceResult from './CompetenceResult.js';
import CompetenceTree from './CompetenceTree.js';
import ComplementaryCertification from './ComplementaryCertification.js';
import ComplementaryCertificationCourse from './ComplementaryCertificationCourse.js';
import ComplementaryCertificationCourseResult from './ComplementaryCertificationCourseResult.js';
import ComplementaryCertificationHabilitation from './ComplementaryCertificationHabilitation.js';
import ComplementaryCertificationScoringCriteria from './ComplementaryCertificationScoringCriteria.js';
import ComplementaryCertificationScoringWithComplementaryReferential from './ComplementaryCertificationScoringWithComplementaryReferential.js';
import ComplementaryCertificationScoringWithoutComplementaryReferential from './ComplementaryCertificationScoringWithoutComplementaryReferential.js';
import Correction from './Correction.js';
import Course from './Course.js';
import DataProtectionOfficer from './DataProtectionOfficer.js';
import Division from './Division.js';
import EmailModificationDemand from './EmailModificationDemand.js';
import EmailingAttempt from './EmailingAttempt.js';
import Examiner from './Examiner.js';
import FinalizedSession from './FinalizedSession.js';
import Framework from './Framework.js';
import Group from './Group.js';
import Hint from './Hint.js';
import JuryCertification from './JuryCertification.js';
import JurySession from './JurySession.js';
import KnowledgeElement from './KnowledgeElement.js';
import LearningContent from './LearningContent.js';
import Membership from './Membership.js';
import NeutralizationAttempt from './NeutralizationAttempt.js';
import Organization from './Organization.js';
import OrganizationForAdmin from './OrganizationForAdmin.js';
import OrganizationInvitation from './OrganizationInvitation.js';
import OrganizationInvitedUser from './OrganizationInvitedUser.js';
import OrganizationLearner from './OrganizationLearner.js';
import OrganizationMemberIdentity from './OrganizationMemberIdentity.js';
import OrganizationPlacesLot from './OrganizationPlacesLot.js';
import OrganizationTag from './OrganizationTag.js';
import OrganizationsToAttachToTargetProfile from './OrganizationsToAttachToTargetProfile.js';
import ParticipantResultsShared from './ParticipantResultsShared.js';
import ParticipationForCampaignManagement from './ParticipationForCampaignManagement.js';
import PartnerCertificationScoring from './PartnerCertificationScoring.js';
import PlacementProfile from './PlacementProfile.js';
import PoleEmploiSending from './PoleEmploiSending.js';
import PrivateCertificate from './PrivateCertificate.js';
import Progression from './Progression.js';
import ReproducibilityRate from './ReproducibilityRate.js';
import ResultCompetence from './ResultCompetence.js';
import ResultCompetenceTree from './ResultCompetenceTree.js';
import SCOCertificationCandidate from './SCOCertificationCandidate.js';
import Scorecard from './Scorecard.js';
import ScoringSimulation from './ScoringSimulation.js';
import ScoringSimulationContext from './ScoringSimulationContext.js';
import ScoringSimulationDataset from './ScoringSimulationDataset.js';
import ScoringSimulationResult from './ScoringSimulationResult.js';
import Session from './Session.js';
import SessionJuryComment from './SessionJuryComment.js';
import SessionPublicationBatchResult from './SessionPublicationBatchResult.js';
import ShareableCertificate from './ShareableCertificate.js';
import Skill from './Skill.js';
import SkillSet from './SkillSet.js';
import Solution from './Solution.js';
import Stage from './Stage.js';
import Student from './Student.js';
import SupOrganizationLearner from './SupOrganizationLearner.js';
import SupOrganizationLearnerSet from './SupOrganizationLearnerSet.js';
import Tag from './Tag.js';
import TargetProfile from './TargetProfile.js';
import TargetProfileForAdminNewFormat from './TargetProfileForAdminNewFormat.js';
import TargetProfileForAdminOldFormat from './TargetProfileForAdminOldFormat.js';
import TargetProfileForCreation from './TargetProfileForCreation.js';
import TargetProfileForUpdate from './TargetProfileForUpdate.js';
import TargetProfileSummaryForAdmin from './TargetProfileSummaryForAdmin.js';
import Thematic from './Thematic.js';
import Training from './Training.js';
import TrainingTrigger from './TrainingTrigger.js';
import TrainingTriggerTube from './TrainingTriggerTube.js';
import Tube from './Tube.js';
import Tutorial from './Tutorial.js';
import TutorialEvaluation from './TutorialEvaluation.js';
import User from './User.js';
import UserCompetence from './UserCompetence.js';
import UserDetailsForAdmin from './UserDetailsForAdmin.js';
import UserLogin from './UserLogin.js';
import UserOrgaSettings from './UserOrgaSettings.js';
import UserSavedTutorial from './UserSavedTutorial.js';
import UserSavedTutorialWithTutorial from './UserSavedTutorialWithTutorial.js';
import UserToCreate from './UserToCreate.js';
import Validation from './Validation.js';
import Validator from './Validator.js';
import ValidatorAlwaysOK from './ValidatorAlwaysOK.js';
import ValidatorQCM from './ValidatorQCM.js';
import ValidatorQCU from './ValidatorQCU.js';
import ValidatorQROC from './ValidatorQROC.js';
import ValidatorQROCMDep from './ValidatorQROCMDep.js';
import ValidatorQROCMInd from './ValidatorQROCMInd.js';

export {
  AccountRecoveryDemand,
  AdminMember,
  Answer,
  AnswerCollectionForScoring,
  AnswerStatus,
  Area,
  Assessment,
  AssessmentResult,
  Authentication,
  AuthenticationMethod,
  AuthenticationSessionContent,
  Badge,
  BadgeAcquisition,
  BadgeCriterion,
  BadgeDetails,
  BadgeForCalculation,
  Campaign,
  CampaignCreator,
  CampaignForArchiving,
  CampaignForCreation,
  CampaignLearningContent,
  CampaignParticipant,
  CampaignParticipation,
  CampaignParticipationBadge,
  CampaignParticipationResult,
  CampaignParticipationStatuses,
  CampaignToStartParticipation,
  CampaignTypes,
  CertifiableBadgeAcquisition,
  CertifiableProfileForLearningContent,
  CertificationAnswerStatusChangeAttempt,
  CertificationAssessment,
  CertificationAssessmentScore,
  CertificationAttestation,
  CertificationCandidate,
  CertificationCandidateForSupervising,
  CertificationCenter,
  CertificationCenterForAdmin,
  CertificationCenterInvitation,
  CertificationCenterInvitedUser,
  CertificationCenterMembership,
  CertificationChallenge,
  CertificationChallengeWithType,
  CertificationContract,
  CertificationCourse,
  CertificationCpfCity,
  CertificationCpfCountry,
  CertificationIssueReport,
  CertificationIssueReportCategory,
  CertificationIssueReportResolutionAttempt,
  CertificationIssueReportResolutionStrategies,
  CertificationOfficer,
  CertificationReport,
  CertificationResult,
  CertifiedLevel,
  CertifiedScore,
  Challenge,
  Competence,
  CompetenceEvaluation,
  CompetenceMark,
  CompetenceResult,
  CompetenceTree,
  ComplementaryCertification,
  ComplementaryCertificationCourse,
  ComplementaryCertificationCourseResult,
  ComplementaryCertificationHabilitation,
  ComplementaryCertificationScoringCriteria,
  ComplementaryCertificationScoringWithComplementaryReferential,
  ComplementaryCertificationScoringWithoutComplementaryReferential,
  Correction,
  Course,
  DataProtectionOfficer,
  Division,
  EmailModificationDemand,
  EmailingAttempt,
  Examiner,
  FinalizedSession,
  Framework,
  Group,
  Hint,
  JuryCertification,
  JurySession,
  KnowledgeElement,
  LearningContent,
  Membership,
  NeutralizationAttempt,
  Organization,
  OrganizationForAdmin,
  OrganizationInvitation,
  OrganizationInvitedUser,
  OrganizationLearner,
  OrganizationMemberIdentity,
  OrganizationPlacesLot,
  OrganizationTag,
  OrganizationsToAttachToTargetProfile,
  ParticipantResultsShared,
  ParticipationForCampaignManagement,
  PartnerCertificationScoring,
  PlacementProfile,
  PoleEmploiSending,
  PrivateCertificate,
  Progression,
  ReproducibilityRate,
  ResultCompetence,
  ResultCompetenceTree,
  SCOCertificationCandidate,
  Scorecard,
  ScoringSimulation,
  ScoringSimulationContext,
  ScoringSimulationDataset,
  ScoringSimulationResult,
  Session,
  SessionJuryComment,
  SessionPublicationBatchResult,
  ShareableCertificate,
  Skill,
  SkillSet,
  Solution,
  Stage,
  Student,
  SupOrganizationLearner,
  SupOrganizationLearnerSet,
  Tag,
  TargetProfile,
  TargetProfileForAdminNewFormat,
  TargetProfileForAdminOldFormat,
  TargetProfileForCreation,
  TargetProfileForUpdate,
  TargetProfileSummaryForAdmin,
  Thematic,
  Training,
  TrainingTrigger,
  TrainingTriggerTube,
  Tube,
  Tutorial,
  TutorialEvaluation,
  User,
  UserCompetence,
  UserDetailsForAdmin,
  UserLogin,
  UserOrgaSettings,
  UserSavedTutorial,
  UserSavedTutorialWithTutorial,
  UserToCreate,
  Validation,
  Validator,
  ValidatorAlwaysOK,
  ValidatorQCM,
  ValidatorQCU,
  ValidatorQROC,
  ValidatorQROCMDep,
  ValidatorQROCMInd,
};
