const SESSION_SUPERVISING = {
  INCORRECT_DATA: {
    code: 'INCORRECT_DATA',
    getMessage: () => `Le numéro de session et/ou le mot de passe saisis sont incorrects.`,
  },
};

const MAXIMAL_SESSION_DURATION_IN_MS = 24 * 60 * 60 * 1000; // 24h
const AUTHORIZED_TO_START_DURATION_VALIDITY_IN_MS = 15 * 60 * 1000; // 15min
const MAXIMAL_CERTIFICATION_DURATION_IN_MS = 24 * 60 * 60 * 1000; // 24h

export {
  AUTHORIZED_TO_START_DURATION_VALIDITY_IN_MS,
  MAXIMAL_CERTIFICATION_DURATION_IN_MS,
  MAXIMAL_SESSION_DURATION_IN_MS,
  SESSION_SUPERVISING,
};
