module.exports = function () {
  return {
    'free-brands-svg-icons': ['facebook-f', 'linkedin-in', 'twitter'],
    'free-solid-svg-icons': [
      'arrow-left',
      'arrow-right',
      'arrow-up',
      'bars',
      'bookmark',
      'check',
      'chevron-up',
      'chevron-down',
      'circle-check',
      'circle-exclamation',
      'circle-info',
      'circle-question',
      'circle-user',
      'circle-xmark',
      'copy',
      'eye',
      'eye-slash',
      'globe',
      'hourglass-end',
      'image',
      'link',
      'lock',
      'minus',
      'plus',
      'power-off',
      'right-from-bracket',
      'right-long',
      'rotate-right',
      'times-circle',
      'thumbs-up',
      'triangle-exclamation',
      'up-right-from-square',
      'user',
      'xmark',
    ],
    'free-regular-svg-icons': ['bookmark', 'clock', 'copy', 'thumbs-up'],
  };
};
