module.exports = function () {
  return {
    'free-brands-svg-icons': ['facebook-f', 'linkedin-in', 'twitter'],
    'free-solid-svg-icons': [
      'arrow-left',
      'arrow-right',
      'bars',
      'bookmark',
      'circle-check',
      'copy',
      'circle-exclamation',
      'triangle-exclamation',
      'up-right-from-square',
      'eye',
      'eye-slash',
      'hourglass-end',
      'image',
      'info-circle',
      'question-circle',
      'lock',
      'long-arrow-alt-right',
      'power-off',
      'redo-alt',
      'sign-out-alt',
      'thumbs-up',
      'times',
      'times-circle',
      'chevron-down',
      'user',
      'user-circle',
      'link',
      'globe',
    ],
    'free-regular-svg-icons': ['bookmark', 'copy', 'thumbs-up'],
  };
};
