#!/bin/sh

case "$OSTYPE" in
  darwin*) SED=gsed ;;
  *) SED=sed ;;
esac

pnpm import

# Update buildpack
find . -regex ".*node_modules*" -prune -o -name .buildpacks -exec $SED -i 's#Scalingo/nodejs#1024pix/nodejs#' {} \;

# Update npm run
find . -regex ".*node_modules*" -prune -o -name package.json -exec $SED -i 's#npm run#pnpm run#' {} \;

# Update npx
find . -regex ".*node_modules*" -prune -o -name package.json -exec $SED -i 's#npx#pnpm dlx#' {} \;

# Remove package-lock.json files
find . -regex ".*node_modules*" -prune -o -name package-lock.json -exec git rm {} \;
