import { CERTIFICATIONS_DATA } from '../db-data.ts';

export const pixCertifiableUserData = [
  {
    firstName: 'Buffy',
    lastName: 'Summers',
    email: 'buffy.summers@example.net',
    rawPassword: 'pix123',
    sex: 'F',
    birthdate: '1981-01-19',
    birthDay: '19',
    birthMonth: '01',
    birthYear: '1981',
    birthCountry: 'FRANCE',
    birthCity: 'Perpignan',
    postalCode: '66000',
  },
  {
    firstName: 'Rupert',
    lastName: 'Giles',
    email: 'rupert.giles@example.net',
    rawPassword: 'pix123',
    sex: 'M',
    birthdate: '1955-02-22',
    birthDay: '22',
    birthMonth: '02',
    birthYear: '1955',
    birthCountry: 'FRANCE',
    birthCity: 'Perpignan',
    postalCode: '66000',
  },
  {
    firstName: 'Cordelia',
    lastName: 'Chase',
    email: 'cordelia.chase@example.net',
    rawPassword: 'pix123',
    sex: 'F',
    birthdate: '1981-08-05',
    birthDay: '05',
    birthMonth: '08',
    birthYear: '1981',
    birthCountry: 'FRANCE',
    birthCity: 'Perpignan',
    postalCode: '66000',
  },
  {
    firstName: 'Willow',
    lastName: 'Rosenberg',
    email: 'willow.rosenberg@example.net',
    rawPassword: 'pix123',
    sex: 'F',
    birthdate: '1983-12-15',
    birthDay: '15',
    birthMonth: '12',
    birthYear: '1983',
    birthCountry: 'FRANCE',
    birthCity: 'Perpignan',
    postalCode: '66000',
  },
  {
    firstName: 'Riley',
    lastName: 'Finn',
    email: 'riley.finn@example.net',
    rawPassword: 'pix123',
    sex: 'M',
    birthdate: '1981-09-29',
    birthDay: '29',
    birthMonth: '09',
    birthYear: '1981',
    birthCountry: 'FRANCE',
    birthCity: 'Perpignan',
    postalCode: '66000',
  },
  {
    firstName: 'Xander',
    lastName: 'Harris',
    email: 'xander.harris@example.net',
    rawPassword: 'pix123',
    sex: 'M',
    birthdate: '1981-01-08',
    birthDay: '08',
    birthMonth: '01',
    birthYear: '1981',
    birthCountry: 'FRANCE',
    birthCity: 'Perpignan',
    postalCode: '66000',
  },
  {
    firstName: 'William',
    lastName: 'Pratt',
    email: 'william.pratt@example.net',
    rawPassword: 'pix123',
    sex: 'M',
    birthdate: '1853-05-10',
    birthDay: '10',
    birthMonth: '05',
    birthYear: '1853',
    birthCountry: 'FRANCE',
    birthCity: 'Perpignan',
    postalCode: '66000',
  },
];

export const PIX_ADMIN_CERTIF_DATA = {
  firstName: 'pixAdminRoleCertif',
  lastName: `pixAdminRoleCertif`,
  email: `pix-admin-role-certif@example.net`,
  rawPassword: 'pix123',
  role: 'CERTIF',
};

export const PIX_CERTIF_PRO_DATA = {
  firstName: 'PixCertif',
  lastName: 'CentrePRO',
  email: 'pix-certif_pro@example.net',
  rawPassword: 'pix123',
  certificationCenters: [
    {
      type: 'PRO',
      externalId: 'CERTIFPRO',
      habilitations: [
        CERTIFICATIONS_DATA.CLEA,
        CERTIFICATIONS_DATA.EDU_1ER_DEGRE,
        CERTIFICATIONS_DATA.DROIT,
        CERTIFICATIONS_DATA.PRO_SANTE,
      ],
      withOrganization: {
        isManagingStudents: false,
      },
    },
  ],
};

export const PIX_CERTIF_SCO_DATA = {
  firstName: 'PixCertif',
  lastName: 'CentreSCO',
  email: 'pix-certif_sco@example.net',
  rawPassword: 'pix123',
  certificationCenters: [
    {
      type: 'SCO',
      externalId: 'CERTIFSCO',
      habilitations: [],
      withOrganization: {
        isManagingStudents: true,
      },
    },
  ],
};
