export const EVENT_NAMES = Object.freeze({
  CANDIDATE_ENROLLED_INDIVIDUAL: 'CANDIDATE_ENROLLED_INDIVIDUAL',
  CANDIDATE_ENROLLED_ODS: 'CANDIDATE_ENROLLED_ODS',
  CANDIDATE_ENROLLED_CSV: 'CANDIDATE_ENROLLED_CSV',
  CANDIDATE_ENROLLED_SCO: 'CANDIDATE_ENROLLED_SCO',
  CANDIDATE_RECONCILED: 'CANDIDATE_RECONCILED',
  CANDIDATE_AUTHORIZED_TO_START: 'CANDIDATE_AUTHORIZED_TO_START',
  CANDIDATE_AUTHORIZED_TO_RESUME: 'CANDIDATE_AUTHORIZED_TO_RESUME',
  CANDIDATE_UNAUTHORIZED_TO_START: 'CANDIDATE_UNAUTHORIZED_TO_START',
});
