export const EVENT_NAMES = Object.freeze({
  CANDIDATE_ENROLLED_INDIVIDUAL: 'CANDIDATE_ENROLLED_INDIVIDUAL',
  CANDIDATE_ENROLLED_ODS: 'CANDIDATE_ENROLLED_ODS',
  CANDIDATE_ENROLLED_CSV: 'CANDIDATE_ENROLLED_CSV',
  CANDIDATE_ENROLLED_SCO: 'CANDIDATE_ENROLLED_SCO',
});
