#!/usr/bin/env bash

set -eo pipefail

# In case filename contains spaces [https://www.baeldung.com/linux/reading-output-into-array#1-output-may-contain-spaces](https://www.baeldung.com/linux/reading-output-into-array#1-output-may-contain-spaces)
IFS=$'\n'

CHANGED_FILES=($(git diff --name-only --cached --diff-filter=ACMR))

# This SECRET value is in the referential
SECRET=postgres://postgres:J9FUMSBhei8oU@db.dbhostprovider.com:5434/thedb

RED='\033[0;31m'
NO_COLOR='\033[0m'

for file in "${CHANGED_FILES[@]}"
do
# GREEN='\033[0;32m'
#  echo -e "Inspecting file : ${GREEN} ${file} ${NO_COLOR}"
  MATCHES="$(grep --count "$SECRET" "${file}" || true)"
  if [ "$MATCHES" -gt 0 ]
    then
      echo -e "Oops, we found the secret ${RED} ${SECRET} ${NO_COLOR} in file ${file} ! "
      exit 255
  fi
done
