#!/bin/sh

set -e

pnpm exec lint-staged --cwd junior
pnpm exec lint-staged --cwd admin
pnpm exec lint-staged --cwd certif
pnpm exec lint-staged --cwd mon-pix
pnpm exec lint-staged --cwd orga
pnpm exec lint-staged
