#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npx lint-staged --cwd 1d
npx lint-staged --cwd admin
npx lint-staged --cwd certif
npx lint-staged --cwd mon-pix
npx lint-staged --cwd orga
npx lint-staged

.husky/detect-secret
