#!/usr/bin/env bash

current_branch=$(git rev-parse --abbrev-ref HEAD)

protected_branch=dev

[[ $current_branch = "${protected_branch}" ]] && {
 echo "You're trying to push to protected branch \"${protected_branch}\""
 echo "If you need to enforce, use --no-verify option"
 exit 1
}

exit 0

