apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: pix
  labels:
    app: mon-pix
    app.kubernetes.io/name: mon-pix
    app.kubernetes.io/part-of: pix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mon-pix
  template:
    metadata:
      labels:
        app: mon-pix
    spec:
      volumes:
        - name: config
          configMap:
            name: nginx-config
            items:
              - key: "nginx.conf"
                path: "default.conf"
      containers:
        - name: mon-pix
          image: pix-mon-pix:dev
          imagePullPolicy: Never
          volumeMounts:
            - mountPath: /etc/nginx/conf.d/
              name: config
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: mon-pix-config
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "512Mi"
              cpu: "1"
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: mon-pix
  namespace: pix
  labels:
    app: mon-pix
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: mon-pix
