module.exports = function () {
  return {
    'free-solid-svg-icons': [
      'archive',
      'arrow-down',
      'arrow-left',
      'arrow-right',
      'arrow-up',
      'award',
      'book',
      'bullhorn',
      'chevron-down',
      'chevron-up',
      'crown',
      'ellipsis-v',
      'eye',
      'eye-slash',
      'exclamation-triangle',
      'exclamation-circle',
      'external-link-alt',
      'hourglass-half',
      'info-circle',
      'link',
      'minus',
      'mobile-alt',
      'percent',
      'plus',
      'power-off',
      'question-circle',
      'search',
      'share',
      'share-square',
      'slash',
      'star',
      'tablet-alt',
      'times',
      'users',
      'trash-alt',
    ],
    'free-regular-svg-icons': ['check-circle', 'copy', 'trash-alt'],
  };
};
