export const IMPORT_STATUSES = {
  UPLOADED: 'UPLOADED',
  UPLOAD_ERROR: 'UPLOAD_ERROR',
  VALIDATED: 'VALIDATED',
  IMPORTED: 'IMPORTED',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  IMPORT_ERROR: 'IMPORT_ERROR',
};

export const IMPORT_KEY_FIELD = {
  COMMON_FIRSTNAME: 'COMMON_FIRSTNAME',
  COMMON_LASTNAME: 'COMMON_LASTNAME',
  COMMON_BIRTHDATE: 'COMMON_BIRTHDATE',
  COMMON_DIVISION: 'COMMON_DIVISION',
};
