export const IMPORT_STATUSES = {
  UPLOADING: 'UPLOADING',
  UPLOADED: 'UPLOADED',
  UPLOAD_ERROR: 'UPLOAD_ERROR',
  VALIDATED: 'VALIDATED',
  IMPORTED: 'IMPORTED',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  IMPORT_ERROR: 'IMPORT_ERROR',
};

export const IMPORT_KEY_FIELD = {
  COMMON_FIRSTNAME: 'COMMON_FIRSTNAME',
  COMMON_LASTNAME: 'COMMON_LASTNAME',
  COMMON_BIRTHDATE: 'COMMON_BIRTHDATE',
  COMMON_DIVISION: 'COMMON_DIVISION',
};

export const SUP_IMPORT_TYPES = {
  ADDITIONAL_STUDENT: 'ADDITIONAL_STUDENT',
  REPLACE_STUDENT: 'REPLACE_STUDENT',
};

export const ANONYMIZATION_RULE = {
  KEEP: 'keep',
  CLEAR: 'clear',
  GENERALIZE_DATE: 'generalize_date',
};
