export const IMPORT_STATUSES = {
  UPLOADING: 'UPLOADING',
  UPLOADED: 'UPLOADED',
  UPLOAD_ERROR: 'UPLOAD_ERROR',
  VALIDATED: 'VALIDATED',
  IMPORTED: 'IMPORTED',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  IMPORT_ERROR: 'IMPORT_ERROR',
};

export const IMPORT_KEY_FIELD = {
  COMMON_FIRSTNAME: 'COMMON_FIRSTNAME',
  COMMON_LASTNAME: 'COMMON_LASTNAME',
  COMMON_BIRTHDATE: 'COMMON_BIRTHDATE',
  COMMON_DIVISION: 'COMMON_DIVISION',
};

export const SUP_IMPORT_TYPES = {
  ADDITIONAL_STUDENT: 'ADDITIONAL_STUDENT',
  REPLACE_STUDENT: 'REPLACE_STUDENT',
};

export const ANONYMIZATION_RULE = {
  KEEP: 'keep',
  CLEAR: 'clear',
  GENERALIZE_DATE: 'generalize_date',
};

export const SIECLE_ERRORS = {
  INE_REQUIRED: 'INE_REQUIRED',
  INE_UNIQUE: 'INE_UNIQUE',
  SEX_CODE_REQUIRED: 'SEX_CODE_REQUIRED',
  BIRTH_CITY_CODE_REQUIRED_FOR_FR_STUDENT: 'BIRTH_CITY_CODE_REQUIRED_FOR_FR_STUDENT',
  BIRTHDATE_REQUIRED: 'BIRTHDATE_REQUIRED',
  INVALID_BIRTHDATE_FORMAT: 'INVALID_BIRTHDATE_FORMAT',
  LAST_NAME_REQUIRED: 'LAST_NAME_REQUIRED',
  FIRST_NAME_REQUIRED: 'FIRST_NAME_REQUIRED',
  INVALID_CHAR_DETECTED: 'INVALID_CHAR_DETECTED',
};
