extends: '../.eslintrc.yaml'

globals:
  include: true

rules:
  no-sync: error
  no-restricted-syntax:
     -  error
     -  selector: "CallExpression[callee.object.name='knex'][callee.property.name='raw'][arguments.0.type='TemplateLiteral']"
        message: "do not use template strings with knex.raw to avoid SQL injection"
     # These 2 selectors are duplicated from ../eslintrc.yaml as they are overridden by default
     # TODO: find a way to keep without redefining them
     -  selector: "NewExpression[callee.name=Date][arguments.length=1][arguments.0.type=Literal]:not([arguments.0.value=/^[12][0-9]{3}-(0[0-9]|1[0-2])-([0-2][0-9]|3[01])(T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]Z)?$/])"
        message: "Use only ISO8601 UTC syntax ('2019-03-12T01:02:03Z') in Date constructor"
     -  selector: "CallExpression[callee.object.object.name='faker'][callee.object.property.name='internet'][callee.property.name='email']"
        message: "Use only faker.internet.exampleEmail()"
