extends:
  - ../.eslintrc.yaml
  - 'plugin:i18n-json/recommended'
  - 'plugin:mocha/recommended'
  - 'plugin:prettier/recommended'
  - 'plugin:chai-expect/recommended'
parserOptions:
  ecmaVersion: 2020
  requireConfigFile: false

parser: "@babel/eslint-parser"

globals:
  include: true

plugins:
  - knex
  - node
  - unicorn

rules:
  no-console: error
  mocha/no-hooks-for-single-case: off
  no-sync: error
  no-restricted-syntax:
    - error
    # These 2 selectors are duplicated from ../eslintrc.yaml as they are overridden by default
    # TODO: find a way to keep without redefining them
    - selector: 'NewExpression[callee.name=Date][arguments.length=1][arguments.0.type=Literal]:not([arguments.0.value=/^[12][0-9]{3}-(0[0-9]|1[0-2])-([0-2][0-9]|3[01])(T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]Z)?$/])'
      message: "Use only ISO8601 UTC syntax ('2019-03-12T01:02:03Z') in Date constructor"
    - selector: "CallExpression[callee.object.object.name='faker'][callee.object.property.name='internet'][callee.property.name='email']"
      message: Use only faker.internet.exampleEmail()
  knex/avoid-injections: error
  i18n-json/valid-message-syntax: off
  # Set all recommended rules as blocking for CI
  mocha/no-exclusive-tests: error
  mocha/no-pending-tests: error
  mocha/no-skipped-tests: error
  mocha/no-top-level-hooks: error
  no-empty-function: warn
  # Refer to scripts/_template.js for reliable alternatives to process.exit()
  node/no-process-exit: error
  unicorn/no-empty-file: error
