ls:
  .js: kebab-case
  _test.js: kebab-case

  .dir: kebab-case

  lib:
    application:
      preHandlers:
        .dir: camelCase
      simulateErrors:
        .dir: camelCase

  tests:
    integration:
      application:
        campaignParticipations:
          .dir: camelCase


ignore:
  - .git
  - node_modules
  - .nyc_output
  - db/migrations
  - db/seeds
  - scripts
