name: Notify team if API configuration file has been changed on dev

on:
  push:
    branches:
      - dev

permissions:
  contents: read
  pull-requests: read

jobs:
  check-and-notify:
    name: Check and notify
    runs-on: ubuntu-latest
    steps:
      - name: Run external action
        uses: 1024pix/notify-team-on-config-file-change@v1
        with:
          GITHUB_TOKEN: ${{ github.token }}
          SLACK_BOT_TOKEN: ${{ secrets.PIX_BOT_RUN_SLACK_TOKEN }}
          INTEGRATION_ENV_URL: ${{ secrets.INTEGRATION_ENV_URL }}
