name: Check Inactive Pull Requests

on:
  schedule:
    # Runs every Monday at 9:00 AM
    - cron: '0 9 * * 1'
  # Allow manual execution
  workflow_dispatch:

permissions:
  pull-requests: write
  issues: write
  contents: write

jobs:
  check-inactive-prs:
    runs-on: ubuntu-latest
    steps:
      - uses: 1024pix/pix-actions/close-old-pull-requests@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
