name: Check blocking labels

on:
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled
      - synchronize

jobs:
  check-blocking-labels:
    runs-on: ubuntu-latest
    if: >
      !contains(github.event.pull_request.labels.*.name, ':eyes: Func Review Needed') &&
      !contains(github.event.pull_request.labels.*.name, ':eyes: Design Review Needed') &&
      !contains(github.event.pull_request.labels.*.name, ':eyes: Tech Review Needed') &&
      !contains(github.event.pull_request.labels.*.name, ':warning: Blocked')

    steps:
      - name: Succeed if PR does not contain any Review Label nor Blocked label
        run: |
          echo "La PR ne contient pas de label bloquant"
          exit 0
