name: Move JIRA ticket to Doing
on:
  pull_request:
    types:
      - opened
jobs:
  transition-issue:
    name: Transition Issue
    runs-on: ubuntu-latest
    env:
      JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
      JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
      JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
    steps:
      - name: Login
        if: env.JIRA_BASE_URL != ''
        uses: atlassian/gajira-login@master

      - name: Find Issue Key
        if: env.JIRA_BASE_URL != ''
        id: find
        uses: atlassian/gajira-find-issue-key@master
        continue-on-error: true
        with:
          from: branch

      - name: Transition issue
        uses: atlassian/gajira-transition@master
        if: env.JIRA_BASE_URL != '' && steps.find.outputs.issue
        continue-on-error: true
        with:
          issue: ${{ steps.find.outputs.issue }}
          transition: "Move to 'Doing'"
