name: lint api/lib/domain/usecases new files
on: push
jobs:
  lint-api-lib-staged:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: npm

      - name: Lint api/lib/domain/usecases
        working-directory: ./api
        run: |
          npm ci
          npm run lint:staged:api-lib
