on:
  pull_request:
    types:
      - labeled
      - unlabeled
  check_suite:
    types:
      - completed

jobs:
  check_status:
    runs-on: ubuntu-latest
    steps:
      - name: hello-world
        run: echo "Hello World!"
