name: Merge on Dev
on:
  push:
    branches:
      - dev
      
permissions:
  contents: read

jobs:
  transition-issue:
    name: Transition Issue
    runs-on: ubuntu-latest
    env:
      JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
      JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
      JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
    steps:
      - name: Login
        if: env.JIRA_BASE_URL != ''
        uses: atlassian/gajira-login@master

      - name: Find Issue Key
        if: env.JIRA_BASE_URL != ''
        id: find
        uses: atlassian/gajira-find-issue-key@master
        continue-on-error: true
        with:
          from: commits

      - name: Transition issue
        uses: atlassian/gajira-transition@master
        if: env.JIRA_BASE_URL != '' && steps.find.outputs.issue
        continue-on-error: true
        with:
          issue: ${{ steps.find.outputs.issue }}
          transition: "Move to 'Deployed in Integration'"

  notify-team:
    permissions:
      contents: read
      pull-requests: read
    name: Notify team on config file changed
    runs-on: ubuntu-latest
    steps:
      - name: Notify team on config file change
        uses: 1024pix/notify-team-on-config-file-change@v1.0.3
        with:
          GITHUB_TOKEN: ${{ github.token }}
          SLACK_BOT_TOKEN: ${{ secrets.PIX_BOT_RUN_SLACK_TOKEN }}
          INTEGRATION_ENV_URL: ${{ secrets.INTEGRATION_ENV_URL }}
