on:
  schedule:
    - cron: "0 12 * * *"

jobs:
  cleanup_branches:
    name: "Branch Cleaner"
    runs-on: ubuntu-latest
    steps:
      - name: "Manage Stale Branches"
        id: branch_cleaner
        uses: crazy-matt/manage-stale-branches@1.1.0
        with:
          gh_token: ${{ env.PIX_SERVICE_ACTIONS_TOKEN }}
          stale_older_than: 60
          suggestions_older_than: 30
          dry_run: true
          archive_stale: true
          excluded_branches: |
            origin/main
            origin/master
            origin/dev
