name: Trigger CircleCI

on:
  push:
    branches:
      - dev
  merge_group:
    types: [checks_requested]
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
  issue_comment:
    types: [created]

jobs:
  trigger-ci:
    runs-on: ubuntu-latest

    # Triggered when : on "dev" branch OR in the merge queue OR not a draft PR OR commented with '/run-ci'
    if: >
      github.event_name == 'push' ||
      github.event_name == 'merge_group' ||
      (github.event_name == 'pull_request' && !github.event.pull_request.draft) ||
      (github.event_name == 'issue_comment' && github.event.issue.pull_request && contains(github.event.comment.body, '/run-ci'))

    steps:
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Trigger CircleCI
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.2.0
        with:
          target-branch: ${{ steps.extract_branch.outputs.branch }}
        env:
          CCI_TOKEN: ${{ secrets.PIX_SERVICE_CIRCLE_CI_TOKEN }}
